
---

# infoelectoral <span style="font-size: 50%;">(on GitHub)</span>

.pull-left[
### Authors

- **Héctor Meleiro**

### Key features

- Retrieve election data at municipality level.
- Retrieve election data at polling station level.
- Retrieve election candidates data.
- Provides datasets with administrative codes
  for autonomous communities, provinces, and municipalities,
  as well as median income data for census tracts.
]

.pull-right[
### Data sources

- [Ministerio del Interior](https://infoelectoral.interior.gob.es/opencms/es/inicio/).

### Output formats

- **data.frame**.
]

---

# infoelectoral <span style="font-size: 50%;">(on GitHub)</span>

.pull-left[
### Quick demo

```{r infoelectoral-example, fig.show="hide"}
library(infoelectoral)
library(dplyr)
library(ggplot2)

df <- municipios("congreso", anno="1982", mes="10") |> #<<
  group_by(siglas) |>
  summarise(votos = sum(votos)) |>
  mutate(seats = round(votos / sum(votos) * 350)) |>
  filter(seats >= 10)

df <- ggparliament::parliament_data(
  df, type="semicircle", 7, df$seats)

ggplot(df) +
  aes(x, y, colour = siglas) +
  ggparliament::geom_parliament_seats() + 
  ggparliament::theme_ggparliament() +
  scale_color_manual(values=c(
    "#3399FF", "#3399FF", "#009900", "#0000EB",
    "#F10000", "#F10000", "#F10000", "#FFA500"
  )) +
  theme(legend.position = 'bottom')
```
]

.pull-right[
```{r infoelectoral-plot, echo=FALSE, ref.label="infoelectoral-example"}
detach("package:infoelectoral")
detach("package:dplyr")
```
]
